### PR TITLE
do not rely on remote server when installing package

### PR DESCRIPTION
**Pull request by mcharytoniuk**
I need to install node-unicodetable behind some weird proxy configuration and it is really hard to get through. I managed to install manually downloaded file but it is quite hard to explain to the rest of the team (I work with) with no JavaScript background to dig into node_modules directory and paste some file from unicode.org and then run `npm install` in this directory. 

I think that downloading external files that could change anytime is a very fragile method of installation. I really like your node-slug package, I think you did the great job and I also think that it would be wonderful if node-unicode could stay without external dependencies.

In this pull requeste I embedded `UnicodeData.txt` into the repository and removed file download scenario since it serves no purpose now.

### CODE REVIEW

**Comment by mcharytoniuk** [comment]
I also think that it's related to #16.

**Comment by dodo** [comment]
Thanks for your efforts, but have you tried installing `unicode-data` on your system first?
Because if the download fails it tries to find `UnicodeData.txt` under [fixed system paths](https://github.com/dodo/node-unicodetable/blob/0.6.0/install.js#L15-16).

Let me know if this is working out for you and/or your distribution is missing.

**Comment by mcharytoniuk** [comment]
I have no administrative rights to do this at work.

**Comment by dodo** [comment]
You can now use `NODE_UNICODETABLE_UNICODEDATA_TXT` to manual set the path to the txt file.
Can you live with cc2c681 as being a merge?

**Comment by mcharytoniuk** [comment]
Sure. Makes sense, thanks. :)

**Pull request closed without merging**
